### ISSUE TITLE
Failure of `developer.mozilla.org_en`: Can not serialize <ParseError invalid>

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#159]
https://farm.openzim.org/pipeline/7dd39f31-3223-475a-b522-f2f914deaabc running with zimit2 / warc2zim2 has failed

Error is in warc2zim2:
```
Traceback (most recent call last):
  File "/usr/bin/zimit", line 8, in <module>
    sys.exit(zimit.zimit())
             ^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/zimit/zimit.py", line 584, in zimit
    run(sys.argv[1:])
  File "/app/zimit/lib/python3.11/site-packages/zimit/zimit.py", line 485, in run
    return warc2zim(warc2zim_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/main.py", line 89, in main
    return converter.run()
           ^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/converter.py", line 277, in run
    self.add_items_for_warc_record(record)
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/converter.py", line 490, in add_items_for_warc_record
    payload_item = WARCPayloadItem(
                   ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/items.py", line 72, in __init__
    ).rewrite(self.content)
      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/content_rewriting/html.py", line 76, in rewrite
    self.feed(content)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 164, in goahead
    self.handle_data(rawdata[i:j])
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/content_rewriting/html.py", line 119, in handle_data
    data = self.css_rewriter.rewrite(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/content_rewriting/css.py", line 24, in rewrite
    output = serialize(rules)
             ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/tinycss2/serializer.py", line 16, in serialize
    _serialize_to(nodes, chunks.append)
  File "/app/zimit/lib/python3.11/site-packages/tinycss2/serializer.py", line 116, in _serialize_to
    node._serialize_to(write)
  File "/app/zimit/lib/python3.11/site-packages/tinycss2/ast.py", line 115, in _serialize_to
    raise TypeError('Can not serialize %r' % self)
TypeError: Can not serialize <ParseError invalid>
FATAL: exception not rethrown
```

This looks like a new problem we did not already encountered. Unfortunately as usual WARC files are lost and the scrape takes hours.

**Comment by benoit74** [comment]
I confirm issue is still there with latest `zimit2` / `warc2zim2`

**Comment by benoit74** [comment]
Fixed by https://github.com/openzim/warc2zim/pull/175
