### ISSUE TITLE
Failure of `MDN`: impossible to decode content

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#186]
Last run of MDN recipe (https://farm.openzim.org/pipeline/961a1716-045f-4dc3-a5b3-dc8eb14315a8) failed with a problem while decoding a file.

```
Traceback (most recent call last):
  File "/usr/bin/zimit", line 8, in <module>
    sys.exit(zimit.zimit())
             ^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/zimit/zimit.py", line 611, in zimit
    run(sys.argv[1:])
  File "/app/zimit/lib/python3.11/site-packages/zimit/zimit.py", line 509, in run
    return warc2zim(warc2zim_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/main.py", line 90, in main
    return converter.run()
           ^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/converter.py", line 264, in run
    self.add_items_for_warc_record(record)
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/converter.py", line 493, in add_items_for_warc_record
    payload_item = WARCPayloadItem(
                   ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/items.py", line 38, in __init__
    (self.title, self.content) = Rewriter(path, record, known_urls).rewrite(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/content_rewriting/generic.py", line 44, in rewrite
    return self.rewrite_html(head_template, css_insert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/content_rewriting/generic.py", line 81, in rewrite_html
    to_string(self.content, self.encoding)
  File "/app/zimit/lib/python3.11/site-packages/warc2zim/utils.py", line 111, in to_string
    raise ValueError(f"Impossible to decode content {input_[:200]}")
ValueError: Impossible to decode content b'wOFF\x00\x01\x00\x00\x00\x00Hl\x00\x0f\x00\x00\x00\x00\x88\x8c\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00GDEF\x00\x00\x01X\x00\x00\x00\x81\x00\x00\x00\xb2\x10\xe0\x0f#GPOS\x00\x00\x01\xdc\x00\x00\x13-\x00\x000\xdc^"\xaf GSUB\x00\x00\x15\x0c\x00\x00\x02\xe1\x00\x00\x05\xf2\xc9\x18\xf8jOS/2\x00\x00\x17\xf0\x00\x00\x00`\x00\x00\x00`T@%\x03STAT\x00\x00\x18P\x00\x00\x00H\x00\x00\x00H\xe7\x88\xcc\x17cmap\x00\x00\x18\x98\x00\x00\x02\x18\x00\x00\x02\xc6\xbdK]\xa4gasp\x00\x00\x1a\xb0\x00\x00\x00\x08\x00\x00\x00\x08\x00\x00\x00\x10glyf\x00\x00\x1a\xb8\x00\x00&\xf6\x00\x00B6'
```

This looks like we are trying to decode a WOFF font (see https://www.w3.org/TR/WOFF/#WOFFHeader). I don't know yet why this has been considered as a file to be rewritten.

In addition to fixing the bug, we should display the file location / original URL when such an error is encountered.

**Comment by mgautierfr** [comment]
I have tested with the MDN warc you have made.
Current warc2zim2 branch works on it.

However, there is some entries coming from webarchive (web.archive.org/web/20210620130312im_/https://developer.mozilla.org/static/media/ZillaSlab-Bold.subset.0beac26b.woff2)
which are declared (mimetype) as `binary/octet-stream` or `text/plain`.
Not enough to start a content decoding and (wrong) rewriting, but if headers are not good, maybe the new version of the warc contains woff font declared as `text/html`. To check.

**Comment by benoit74** [comment]
Not reproduced with last run: https://farm.openzim.org/pipeline/c0d7abda-fd9e-482a-9229-d87a2e4def0c
