### ISSUE TITLE
Css transformation fail

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#394]
Let's make use of this detailed log to find out if there's anything to fix. [run](https://farm.zimit.kiwix.org/pipeline/fa89883a-9fbb-4bda-975d-ed9e860a306c/debug)

```
[zimit::2024-09-11 04:29:20,648] INFO:----------
[zimit::2024-09-11 04:29:20,648] INFO:Testing warc2zim args
[zimit::2024-09-11 04:29:20,648] INFO:Running: warc2zim --name=familypornhd.com_f99f7af0 --zim-file=familypornhd.com_f99f7af0.zim --publisher=openZIM --scraper-suffix zimit 2.1.2 --output /output --url https://familypornhd.com
[warc2zim::2024-09-11 04:29:20,654] INFO:Arguments valid, no inputs to process. Exiting with return code 100
[zimit::2024-09-11 04:29:20,655] INFO:Writing progress to /output/task_progress.json
[zimit::2024-09-11 04:29:20,661] INFO:
[zimit::2024-09-11 04:29:20,661] INFO:----------
[zimit::2024-09-11 04:29:20,662] INFO:Output to tempdir: /output/.tmpcji8a2n3 - will keep
[zimit::2024-09-11 04:29:20,662] INFO:Running browsertrix-crawler crawl: crawl --failOnFailedSeed --waitUntil load --depth -1 --timeout 90 --behaviors autoplay,autofetch,siteSpecific --behaviorTimeout 90 --sizeLimit 4294967296 --diskUtilization 90 --timeLimit 7200 --url https://familypornhd.com --userAgentSuffix zimit.kiwix.org+ contact+zimfarm@kiwix.org --mobileDevice Pixel 2 --cwd /output/.tmpcji8a2n3 --statsFilename /output/crawl.json
```

```
[warc2zim::2024-09-11 06:34:05,588] WARNING:Css transformation fails. Fallback to regex rewriter.
Article path is HttpUrl(https://video-mart.com/video/1c9ac0159c94d8d0cbedc973445af2da)
[warc2zim::2024-09-11 06:34:05,917] ERROR:Problem encountered while processing https://stream-glow.com/cdn/down/eb9cc1c4c2a386eadc1efd086f9c9328/Video/360p/360p_002.html.
Traceback (most recent call last):
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 384, in run
    self.add_items_for_warc_record(record)
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 946, in add_items_for_warc_record
    payload_item = WARCPayloadItem(
                   ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/items.py", line 56, in __init__
    ).rewrite(pre_head_template, post_head_template)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 108, in rewrite
    return self.rewrite_html(pre_head_template, post_head_template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 247, in rewrite_html
    ).rewrite(self.content_str)
      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/html.py", line 130, in rewrite
    self.feed(content)
  File "/usr/lib/python3.12/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/lib/python3.12/html/parser.py", line 179, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/html/parser.py", line 264, in parse_html_declaration
    return self.parse_marked_section(i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_markupbase.py", line 144, in parse_marked_section
    sectName, j = self._scan_name( i+3, i )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_markupbase.py", line 390, in _scan_name
    raise AssertionError(
AssertionError: expected name token at '<![Ö\x81Ðir\x0c¡h×jÀ\x17¸þç°1'
[warc2zim::2024-09-11 06:34:05,925] DEBUG:### REC Headers ###
WARC/1.1
WARC-Page-ID: 39552178-ddea-42b3-b594-1ee1efeb10eb
WARC-Resource-Type: xhr
WARC-JSON-Metadata: {"ipType":"Public","cert":{"issuer":"WE1","ctc":"1"}}
WARC-Target-URI: https://stream-glow.com/cdn/down/eb9cc1c4c2a386eadc1efd086f9c9328/Video/360p/360p_002.html
WARC-Date: 2024-09-11T04:52:58.116Z
WARC-Type: response
WARC-Record-ID: <urn:uuid:169e5900-5e01-4629-85ee-002518aa3cec>
Content-Type: application/http; msgtype=response
WARC-Payload-Digest: sha256:da4b410aaf0aa5bf69d4d18cea1b9cef3c5795451abc22d4d70c892d920127f6
WARC-Block-Digest: sha256:3226eea84e1929aeb6521623c3a0b0e0a0d5e4608eb4d1ebefa129b36e6880ab
Content-Length: 67513

### HTTP Headers ###
HTTP/1.1 200 OK
date: Wed, 11 Sep 2024 04:52:58 GMT
x-content-type-options: nosniff
cf-cache-status: HIT
last-modified: Sun, 08 Sep 2024 05:08:19 GMT
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
age: 256253
vary: Accept-Encoding
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=7rf5yRIV6cyABpOunwfiVO81Q8RYbekHA39KIfVEWrT7nbj88qdf2Mh%2BMkB%2BY11R8GjHvCu0i%2BwaVFrpZ0w5fZNSPSal%2Fja4S%2BTSK6jRn2Yople%2BQg3KRPMWn%2FCfdIrgTxQ%3D"}],"group":"cf-nel","max_age":604800}
content-type: text/html
access-control-allow-origin: https://video-mart.com
cache-control: public, max-age=31536000, s-maxage=31536000
cf-ray: 8c150d277b7f6f5e-CDG
alt-svc: h3=":443"; ma=86400
x-orig-content-encoding: br

### Content ###
Content has been stored b64-encoded at /output/fails/a8ed1c0c-12e8-4fd8-a15a-b8a4a5b04c56.html
[warc2zim::2024-09-11 06:34:05,925] ERROR:Scraper will stop. Pass --verbose flag for more details.
Traceback (most recent call last):
  File "/usr/bin/zimit", line 8, in <module>
    sys.exit(zimit.zimit())
             ^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 688, in zimit
    run(sys.argv[1:])
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 609, in run
    return warc2zim(warc2zim_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/main.py", line 168, in main
    return converter.run()
           ^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 384, in run
    self.add_items_for_warc_record(record)
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 946, in add_items_for_warc_record
    payload_item = WARCPayloadItem(
                   ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/items.py", line 56, in __init__
    ).rewrite(pre_head_template, post_head_template)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 108, in rewrite
    return self.rewrite_html(pre_head_template, post_head_template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 247, in rewrite_html
    ).rewrite(self.content_str)
      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/html.py", line 130, in rewrite
    self.feed(content)
  File "/usr/lib/python3.12/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/lib/python3.12/html/parser.py", line 179, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/html/parser.py", line 264, in parse_html_declaration
    return self.parse_marked_section(i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_markupbase.py", line 144, in parse_marked_section
    sectName, j = self._scan_name( i+3, i )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/_markupbase.py", line 390, in _scan_name
    raise AssertionError(
AssertionError: expected name token at '<![Ö\x81Ðir\x0c¡h×jÀ\x17¸þç°1'
```

**Comment by benoit74** [comment]
Failing resource is at https://stream-glow.com/cdn/down/eb9cc1c4c2a386eadc1efd086f9c9328/Video/360p/360p_002.html

Content type returned by the server is `content-type: text/html`

While in fact it is a video:
```
ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, mpegts, from '360p_002.html':
  Duration: 00:00:02.00, start: 4.070733, bitrate: 266 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 640x360 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn
```

This is the "classic" lying server issue. Not something we know how to handle / want to fix.

Thank you for reporting, this could have been more interesting ^^
