### ISSUE TITLE
Unsupported `..` in query string: segment in cannot be walked

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#423]
https://farm.zimit.kiwix.org/pipeline/dac4c413-0fb5-4371-a856-cadc8e12ad7c/debug

```
[warc2zim::2024-11-19 06:54:55,260] DEBUG:### REC Headers ###
WARC/1.1

WARC-Page-ID: 416e95c5-7467-4173-812d-c13757298779

WARC-Resource-Type: document

WARC-JSON-Metadata: {"ipType":"Public","cert":{"issuer":"R11","ctc":"0"}}

WARC-Target-URI: https://wikileaks.org/pdfjs/web/viewer.html?file=/../spyfiles/files/0/289_GAMMA-201110-FinSpy.pdf

WARC-Date: 2024-11-19T05:36:30.062Z

WARC-Type: response

WARC-Record-ID: <urn:uuid:203075ba-ef97-430f-82a0-1de83831bc31>

Content-Type: application/http; msgtype=response

WARC-Payload-Digest: sha256:ceacb542dc6931476349b523ae9017c66a257a6daf43d810f547223ba1adfc8c

WARC-Block-Digest: sha256:10f30686f527f21860788aaca83c13ffb53e2885faecc276e24d715044e0c2cd

Content-Length: 19878


### HTTP Headers ###
HTTP/1.1 200 OK

age: 23330

cache-control: public, max-age=1200

content-type: text/html; charset=utf-8

date: Tue, 19 Nov 2024 05:36:30 GMT

server: nginx

surrogate-control: ESI/1.0

vary: Accept-Encoding, Accept-Encoding

via: 1.1 varnish (Varnish/7.1)

x-varnish: 26651557 38870741

x-orig-content-encoding: gzip


### Content ###
Content has been stored b64-encoded at /output/fails/b308da33-4a70-4e8e-8562-a4222548f6c5.html
[warc2zim::2024-11-19 06:54:55,261] ERROR:Scraper will stop. Pass --verbose flag for more details.
[zimit::2024-11-19 06:54:55,268] INFO:
[zimit::2024-11-19 06:54:55,268] INFO:
[zimit::2024-11-19 06:54:55,268] INFO:SIGINT/SIGTERM received, stopping zimit
[zimit::2024-11-19 06:54:55,268] INFO:
[zimit::2024-11-19 06:54:55,269] INFO:
```

```
Traceback (most recent call last):
  File "/usr/bin/zimit", line 8, in <module>
    sys.exit(zimit.zimit())
             ^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 688, in zimit
    run(sys.argv[1:])
  File "/app/zimit/lib/python3.12/site-packages/zimit/zimit.py", line 609, in run
    return warc2zim(warc2zim_args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/main.py", line 168, in main
    return converter.run()
           ^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 384, in run
    self.add_items_for_warc_record(record)
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/converter.py", line 946, in add_items_for_warc_record
    payload_item = WARCPayloadItem(
                   ^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/items.py", line 56, in __init__
    ).rewrite(pre_head_template, post_head_template)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 108, in rewrite
    return self.rewrite_html(pre_head_template, post_head_template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/content_rewriting/generic.py", line 225, in rewrite_html
    rel_static_prefix = self.url_rewriter.get_document_uri(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/zimit/lib/python3.12/site-packages/warc2zim/url_rewriting.py", line 354, in get_document_uri
    PurePosixPath(item_url).relative_to(
  File "/usr/lib/python3.12/pathlib.py", line 684, in relative_to
    raise ValueError(f"'..' segment in {str(other)!r} cannot be walked")
ValueError: '..' segment in 'wikileaks.org/pdfjs/web/viewer.html?file=/../spyfiles/files/0' cannot be walked

```

**Comment by benoit74** [comment]
Indeed
