### ISSUE TITLE
Translations won't load if locale is not available.

### ISSUE THREAD

**Issue by ikreymer** [openzim/warc2zim#46]
The `fr` translations are not being loaded if a particular locale is not available.

On a cloud Ubuntu machine, I get:
```
>>> locale.setlocale(locale.LC_ALL, ('fr', 'UTF-8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ilya/venv/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

although, it does work on my own machine.

The translation should not require system locale to be installed.

The original implementation of localizations did not depend on the system locale being available, but simply used
`Translations.load()`

For example, the following could work:

```
locale = lang_data.get("iso-639-1")
env.install_gettext_translations(Translations.load(pathlib.Path(__file__).parent / "locale", locale))
```

Also, it seems we are mixing both 3 and 2 letter language code, seems that makes things more complicated than needed?

Assigning to you for best way to fix this :)

**Comment by rgaudin** [comment]
OK there are two different things here:

* **Translation should not require system locale to be installed**. I disagree with this. The current i18n strings are *accidentally* not using anything from the locale but it could and then if you don't have the locale you get partially localized content.
This behavior is clear and easily fixable (locales are installed in the docker image for that reason).
What you propose mean having to worry about what to put into the templates or not easily detect that you needed the locale.
* **Mixing 2 and 3 letters codes**. We're not mixing them. ZIM spec requires using 3-letters code which is too specific to use for locale so we infer the 2 letters code from it and use it as locale. We could have different parameters (youtube scraper allows setting the locale to override this) but I don't think we need that here.

I'm leaving that open for now so we can think about it.

**Comment by ikreymer** [comment]
> OK there are two different things here:
> 
> * **Translation should not require system locale to be installed**. I disagree with this. The current i18n strings are _accidentally_ not using anything from the locale but it could and then if you don't have the locale you get partially localized content.
>   This behavior is clear and easily fixable (locales are installed in the docker image for that reason).
>   What you propose mean having to worry about what to put into the templates or not easily detect that you needed the locale.

If this is the desired behavior, it probably should be documented.. I spent time trying to figure out why it works on one machine but not another. I think if installing with pip, then specifying `--lang fra` and seeing that the `locale/fr/` strings are there, the localization should work, regardless of what is installed on the system.

I also had a test:

```
         assert self.get_article(zim_output, "M/Language") == b"fra"
 
+        assert "Désolé, l'adresse".encode("utf-8") in self.get_article(zim_output, "A/404.html")
```

that would fail if the locale is not installed, but this seems confusing, since the language is set.

I think the bigger issue is probably that these error messages shouldn't be in the ZIM at all, and we are confusing the language of the site with the language of the reader.

The *text indexing* should match the language of the site. But the *error messages* should depend on language of the *reader*, (kiwix-serve) not the ZIM.  If I crawl a French site, but my viewer locale is set to English, I should see messages in English, or if my locale is in Chinese, the error messages should be in Chinese, etc...


> * **Mixing 2 and 3 letters codes**. We're not mixing them. ZIM spec requires using 3-letters code which is too specific to use for locale so we infer the 2 letters code from it and use it as locale. We could have different parameters (youtube scraper allows setting the locale to override this) but I don't think we need that here.
> 

If using 3-letter `fra` then maybe the directory should also be `locale/fra` not `locale/fr`.

> I'm leaving that open for now so we can think about it.

**Comment by rgaudin** [comment]
> If this is the desired behavior, it probably should be documented.. I spent time trying to figure out why it works on one machine but not another. I think if installing with pip, then specifying `--lang fra` and seeing that the `locale/fr/` strings are there, the localization should work, regardless of what is installed on the system.

Agrees, will update the readme.

> I also had a test:

Good call.

> I think the bigger issue is probably that these error messages shouldn't be in the ZIM at all, and we are confusing the language of the site with the language of the reader.

Agrees. We could manage those separately or even rely on browser's language for this particular reader but we've seen from other ZIMs that content language is *good enough* for UI and is easier to maintain.
That can be improved later on.

> > * **Mixing 2 and 3 letters codes**. We're not mixing them. ZIM spec requires using 3-letters code which is too specific to use for locale so we infer the 2 letters code from it and use it as locale. We could have different parameters (youtube scraper allows setting the locale to override this) but I don't think we need that here.

> If using 3-letter `fra` then maybe the directory should also be `locale/fra` not `locale/fr`.

No those codes are not equivalent. Two letters `ar` for example is Arabic at large while the three letter ones are country specific with major differences. We know we won't maintain those so we maintain an `ar` one that is readable by all ar* readers. System locale also uses a different naming for those so we can only use `ar_TN` in locale-world and not the ISO code.

**Comment by kelson42** [comment]
I'm not sure about what is left to do here.
