### ISSUE TITLE
Crash with error: AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#79]
Warc2zim crashes at https://farm.youzim.it/pipeline/5dab87c4920ec7438c37bff5/debug

with:
```
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/players/dungeoneering/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/howtoplay/adventure/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/gamemasters/encounterdesign/
[DEBUG] Skipping self-redirect: http://rpgbot.net/general/gamemasters/playerarchetypes/
[DEBUG] Skipping self-redirect: http://rpgbot.net/general/gamemasters/pregamesurvery/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/custom-lineage
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/custom-lineage/
[DEBUG] Skipping self-redirect: http://rpgbot.net/p2/characters/classes/monk/
[DEBUG] Skipping self-redirect: http://rpgbot.net/p2/characters/classes/fighter/
[DEBUG] Skipping duplicate https://rpgbot.net/p2/characters/ancestries/duskwalker/, already added to ZIM
[DEBUG] Skipping self-redirect: http://rpgbot.net/p2/characters/ancestries/human/
[DEBUG] Skipping self-redirect: http://rpgbot.net/p2/characters/classes/swashbuckler
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/locathah
[DEBUG] Skipping duplicate https://rpgbot.net/dnd5/characters/races/locathah/, already added to ZIM
[DEBUG] Skipping self-redirect: http://rpgbot.net/p2/characters/ancestries/catfolk
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/Centaur
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/satyr
[DEBUG] Skipping duplicate https://rpgbot.net/dnd5/characters/races/gnome/, already added to ZIM
[DEBUG] Skipping duplicate https://rpgbot.net/dnd5/characters/races/firbolg/, already added to ZIM
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/dragonborn/
[DEBUG] Skipping duplicate https://rpgbot.net/pathfinder/characters/prestigeclasses/mystic_theurge/, already added to ZIM
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/human/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/unchained_monk/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/alchemist/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd35/characters/prestigeclasses/unseenseer/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/prestigeclasses/veiled_illusionist/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd35/characters/classes/warlock/
[DEBUG] Skipping duplicate https://rpgbot.net/general/gamemasters/pregamesurvery/, already added to ZIM
[DEBUG] Skipping self-redirect: http://rpgbot.net/general/worldbuilding/prehistory/
[DEBUG] Skipping duplicate https://rpgbot.net/dnd5/characters/races/aasimar/, already added to ZIM
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/bard/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/brawler/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/gunslinger/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/kineticist/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/magus/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/medium/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/occultist/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/wizard/
[DEBUG] Skipping self-redirect: http://rpgbot.net/pathfinder/characters/classes/samurai/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/dungeonmasters/
[DEBUG] Skipping self-redirect: http://rpgbot.net/p2/how-to-play/
[DEBUG] Skipping duplicate https://rpgbot.net/dnd5/characters/races/locathah, already added to ZIM
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/locathah/
[DEBUG] Skipping self-redirect: http://rpgbot.net/p2/characters/ancestries/gnome/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/vedalken/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/classes/cleric/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/classes/fighter/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/classes/paladin/
[DEBUG] Skipping self-redirect: http://rpgbot.net/dnd5/characters/races/tiefling/
[DEBUG] Skipping duplicate https://rpgbot.net/pathfinder/players/, already added to ZIM
Traceback (most recent call last):
  File "/usr/bin/zimit", line 315, in <module>
    zimit()
  File "/usr/bin/zimit", line 256, in zimit
    return warc2zim(warc2zim_args)
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 711, in warc2zim
    return warc2zim.run()
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 409, in run
    for article in self.generate_all_articles():
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 530, in generate_all_articles
    yield from self.articles_for_warc_record(record)
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 581, in articles_for_warc_record
    if self.is_self_redirect(record, url):
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 563, in is_self_redirect
    return canonicalize(url) == canonicalize(location)
  File "/usr/local/lib/python3.8/site-packages/warc2zim/main.py", line 719, in canonicalize
    if url.startswith("https://"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by rgaudin** [comment]
Fixed it in 0eaedad but I'm puzzled about why we have a WARC record with a `WARC-Target-URI` of `None`.
@ikreymer do you know when this can happen?
