### ISSUE TITLE
Recipe "lesfondamentaux" newly fails

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#82]
From https://farm.openzim.org/pipeline/1462d394a1cb4c4a8cd25a06/debug

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.40/containers/create?name=1462d_zimup_les-fondamentaux_fr_all_%7Bperiod%7D.zim

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 596, in run
    self.handle_files()  # rescan folder
  File "/usr/src/app/task/worker.py", line 545, in handle_files
    self.upload_files()
  File "/usr/src/app/task/worker.py", line 541, in upload_files
    self.start_uploader(self.task["config"]["warehouse_path"], zim_file)
  File "/usr/src/app/task/worker.py", line 316, in start_uploader
    self.uploader = start_uploader(
  File "/usr/src/app/common/docker.py", line 511, in start_uploader
    return run_container(
  File "/usr/src/app/common/docker.py", line 86, in run_container
    return retried_docker_call(docker_client.containers.run, *args, **kwargs)
  File "/usr/src/app/common/docker.py", line 55, in retried_docker_call
    raise exc
  File "/usr/src/app/common/docker.py", line 44, in retried_docker_call
    return docker_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.40/containers/create?name=1462d_zimup_les-fondamentaux_fr_all_%7Bperiod%7D.zim: Bad Request ("Invalid container name (1462d_zimup_les-fondamentaux_fr_all_{period}.zim), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed")
```

and

```
[2021-05-19 15:27:39,686: INFO] starting zimfarm task-worker for 1462d394a1cb4c4a8cd25a06.
[2021-05-19 15:27:39,687: INFO] configuration:
	username=athena18
	webapi_uri=https://api.farm.openzim.org/v1
	workdir=/data
	task_id=1462d394a1cb4c4a8cd25a06
[2021-05-19 15:27:39,687: INFO] testing workdir at /data…
[2021-05-19 15:27:39,687: INFO] 	workdir is available and writable
[2021-05-19 15:27:39,687: INFO] testing private key at /etc/ssh/keys/zimfarm…
[2021-05-19 15:27:39,687: INFO] 	private key is available and readable
[2021-05-19 15:27:39,687: INFO] testing authentication with https://api.farm.openzim.org/v1…
[2021-05-19 15:27:39,932: INFO] 	authentication successful
[2021-05-19 15:27:39,933: INFO] testing docker API on /var/run/docker.sock…
[2021-05-19 15:27:39,980: INFO] 	docker API access successful
[2021-05-19 15:27:39,981: INFO] Container resources:
	RAM  (total): 8 EiB
	RAM  (avail): 8 EiB
	CPUs: 32
	Disk: 29.75 TiB
[2021-05-19 15:27:39,982: INFO] registering exit signals
[2021-05-19 15:27:39,982: INFO] Fetching task details for 1462d394a1cb4c4a8cd25a06
[2021-05-19 15:27:40,109: INFO] Updating task-status=started
[2021-05-19 15:27:40,409: INFO] Setting-up workdir
[2021-05-19 15:27:40,419: INFO] Starting DNS cache
[2021-05-19 15:27:40,905: DEBUG] DNS Cache started using IPs: ['172.17.0.5']
[2021-05-19 15:27:40,906: INFO] Starting scraper. Expects files at: /mnt/data/kiwix/zimfarm2/data/1462d394a1cb4c4a8cd25a06 
[2021-05-19 15:27:40,909: DEBUG] Pulling image ghcr.io/openzim/zimit:1.1.4
[2021-05-19 15:27:42,315: INFO] Updating task-status=scraper_started
[2021-05-19 15:28:43,204: INFO] reporting 10%
[2021-05-19 15:28:43,204: DEBUG] Submitting scraper progress: 10%
[2021-05-19 15:29:43,884: INFO] reporting 22%
[2021-05-19 15:29:43,885: DEBUG] Submitting scraper progress: 22%
[2021-05-19 15:30:44,514: INFO] reporting 25%
[2021-05-19 15:30:44,514: DEBUG] Submitting scraper progress: 25%
[2021-05-19 15:31:45,153: INFO] reporting 31%
[2021-05-19 15:31:45,153: DEBUG] Submitting scraper progress: 31%
[2021-05-19 15:32:45,780: INFO] reporting 44%
[2021-05-19 15:32:45,780: DEBUG] Submitting scraper progress: 44%
[2021-05-19 15:33:46,412: INFO] reporting 50%
[2021-05-19 15:33:46,413: DEBUG] Submitting scraper progress: 50%
[2021-05-19 15:34:47,117: INFO] reporting 59%
[2021-05-19 15:34:47,117: DEBUG] Submitting scraper progress: 59%
[2021-05-19 15:35:47,719: INFO] reporting 69%
[2021-05-19 15:35:47,720: DEBUG] Submitting scraper progress: 69%
[2021-05-19 15:36:48,369: INFO] reporting 78%
[2021-05-19 15:36:48,369: DEBUG] Submitting scraper progress: 78%
[2021-05-19 15:37:49,033: INFO] reporting 83%
[2021-05-19 15:37:49,033: DEBUG] Submitting scraper progress: 83%
[2021-05-19 15:38:32,584: INFO] Updating task-status=scraper_completed. Exit code: 0
[2021-05-19 15:38:33,003: DEBUG] Dumping docker logs to file…
[2021-05-19 15:38:33,690: DEBUG] Starting log uploader container…
[2021-05-19 15:38:34,163: INFO] ZIM file created: les-fondamentaux_fr_all_{period}.zim, 131.06 MiB
[2021-05-19 15:38:34,417: INFO] Starting uploader for /.hidden/private/les-fondamentaux_fr_all_{period}.zim
[2021-05-19 15:38:34,439: ERROR] Unhandled exception: 400 Client Error for http+docker://localhost/v1.40/containers/create?name=1462d_zimup_les-fondamentaux_fr_all_%7Bperiod%7D.zim: Bad Request ("Invalid container name (1462d_zimup_les-fondamentaux_fr_all_{period}.zim), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed")
[2021-05-19 15:38:34,439: ERROR] 400 Client Error for http+docker://localhost/v1.40/containers/create?name=1462d_zimup_les-fondamentaux_fr_all_%7Bperiod%7D.zim: Bad Request ("Invalid container name (1462d_zimup_les-fondamentaux_fr_all_{period}.zim), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.40/containers/create?name=1462d_zimup_les-fondamentaux_fr_all_%7Bperiod%7D.zim

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 596, in run
    self.handle_files()  # rescan folder
  File "/usr/src/app/task/worker.py", line 545, in handle_files
    self.upload_files()
  File "/usr/src/app/task/worker.py", line 541, in upload_files
    self.start_uploader(self.task["config"]["warehouse_path"], zim_file)
  File "/usr/src/app/task/worker.py", line 316, in start_uploader
    self.uploader = start_uploader(
  File "/usr/src/app/common/docker.py", line 511, in start_uploader
    return run_container(
  File "/usr/src/app/common/docker.py", line 86, in run_container
    return retried_docker_call(docker_client.containers.run, *args, **kwargs)
  File "/usr/src/app/common/docker.py", line 55, in retried_docker_call
    raise exc
  File "/usr/src/app/common/docker.py", line 44, in retried_docker_call
    return docker_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.40/containers/create?name=1462d_zimup_les-fondamentaux_fr_all_%7Bperiod%7D.zim: Bad Request ("Invalid container name (1462d_zimup_les-fondamentaux_fr_all_{period}.zim), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed")
[2021-05-19 15:38:34,444: ERROR] exiting.
[2021-05-19 15:38:34,444: INFO] Trying to upload exception details
[2021-05-19 15:38:34,445: INFO] Updating task-status=failed
```

Same or other problem, the upload took place but the filename is somehow broken: `les-fondamentaux_fr_all_{period}.zim`... Does someone has changed the recipe without testing?

**Comment by rgaudin** [comment]
This is a recipe error. This recipe asks for a ZIM named `les-fondamentaux_fr_all_{period}` which is not an allowed name.

Unlike youtube and ted, zimit scraper doesn't replaces the `{period}` pattern.

Ideally, we should:

- [ ] replace chars not accepted by docker in this upload container name
- [ ] handle the `{period}` in zimit
