### ISSUE TITLE
Bug related to HTTP 300 response

### ISSUE THREAD

**Issue by wsdookadr** [openzim/warc2zim#94]
There's one big WARC I'm currently processing and the following exception occured while running warc2zim on it:
<details>
<summary> startswith exception </summary>

```
[DEBUG] Confirming output is writable using /output/tmp6r1baefx
[DEBUG] Title: Closures and lambdas in C++
[DEBUG] Language: eng
[DEBUG] Favicon: https://www.johndcook.com/blog/wp-content/uploads/2020/01/cropped-favicon_512-32x32.png
Traceback (most recent call last):
  File "/usr/local/bin/warc2zim", line 8, in <module>
    sys.exit(warc2zim())
  File "/usr/local/lib/python3.9/dist-packages/warc2zim/main.py", line 780, in warc2zim
    return warc2zim.run()
  File "/usr/local/lib/python3.9/dist-packages/warc2zim/main.py", line 412, in run
    self.add_items_for_warc_record(record)
  File "/usr/local/lib/python3.9/dist-packages/warc2zim/main.py", line 616, in add_items_for_warc_record
    if self.is_self_redirect(record, url):
  File "/usr/local/lib/python3.9/dist-packages/warc2zim/main.py", line 594, in is_self_redirect
    return canonicalize(url) == canonicalize(location)
  File "/usr/local/lib/python3.9/dist-packages/warc2zim/main.py", line 788, in canonicalize
    if url.startswith("https://"):
AttributeError: 'NoneType' object has no attribute 'startswith'
terminate called without an active exception
```
</details>

I was able to reduce the initial 14 GB WARC file down to a 292 KB WARC file through successive slicing smaller pieces of the initial file and re-running warc2zim on those. 

There are only 7 WARC entries inside of this reduced file:

```
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 200 OK
HTTP/1.1 300 Multiple Choices
HTTP/1.1 200 OK
HTTP/1.1 200 OK
```

The only one standing out is the [HTTP 300 response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/300) that seems to lead to a possibly unexpected code path. I should mention that once the HTTP 300 WARC entry is removed from the file, warc2zim is able to process it without errors.

I'm attaching the reduced WARC file for reproducibility purposes.

Versions used:
- warc2zim 1.4.0 (built using docker as [was recommended here](https://github.com/openzim/warc2zim/issues/93#issuecomment-1156154023))

[temp_slice_1.warc.zip](https://github.com/openzim/warc2zim/files/8931693/temp_slice_1.warc.zip)

**Comment by rgaudin** [comment]
Fixed the bug but [HTTP 300](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/300) being loose on how to offer those choices, result may be unexpected.
In this case, [said URL](https://www.johndcook.com/Beta36.gif) seems automatically generated by the web server to compensate non-rigorous links.
